apiVersion: v1
kind: Pod
metadata:
  name: wrk
  labels:
    purpose: wrk
spec:
  containers:
  - name: wrk
    image: wrk-akka-http-docker:1.0-SNAPSHOT
    args: [
      "-t2",
      "-c100",
      "-d30s",
      "-s",
      "scripts/wrk-script.lua",
      "http://$(AKKA_HTTP_DOCKER_SERVICE_SERVICE_HOST):$(AKKA_HTTP_DOCKER_SERVICE_SERVICE_PORT)/scoring"
    ]
    #args: ["-t2", "-c100", "-d30s", "-s", "scripts/wrk-script.lua",  "http://172.17.0.5:8080/scoring"]
  restartPolicy: OnFailure